### ISSUE TITLE
 SQL injection issue

### ISSUE THREAD

**Issue by d-ruiz** [bxservice/idempiere-rest#1]
Reported by Carlos:

http://localhost:8080/api/v1/forms?filter=IsActive=?);UPDATE AD_User SET Password='MyPassword' WHERE Name='SuperUser'

Any SQL can be added there - I tried also a DROP TABLE instead of the UPDATE and it worked

**Comment by norbertbede** [comment]
hi @d-ruiz,

do you have any plan to fix this issue ? 
We would like to use the REST API in production from October. 
can we help somehow with this issue?

Norbert

**Comment by d-ruiz** [comment]
From the meeting on 08.10.2020

We implement the idea mentioned in https://github.com/bxservice/idempiere-rest/issues/10

xref -> https://mattermost.idempiere.org/idempiere/pl/sz5s48pzjpntipmo76cxttrmth
