### ISSUE TITLE
Filter Improvement, replace WHERE SQL

### ISSUE THREAD

**Issue by norbertbede** [bxservice/idempiere-rest#10]
ATM  if we want filter data, then we need to use SQL syntax. This is not typical, frontend developer doesn't understand.

Would be better to implement a layer that transforms REST odata logic to SQL syntax.

**example**
https://www.odata.org/getting-started/basic-tutorial/#filter

**mentioned here**
https://github.com/bxservice/idempiere-rest/issues/4

**Comment by CarlosRuiz-globalqss** [comment]
Hi @norbertbede - this sounds interesting as it can be a solution for #1 too

**Comment by d-ruiz** [comment]
Please see the attached pull request. 

It follows the oData 4 syntax. Supported functions:
- contains
- tolower
- toupper
- startswith
- endswith

Things that have not been implemented: 

- Aliases
- Child columns
 f.i: 
 The request below returns airports with "San Francisco" contained in its Address. And Address is property of complex type Location. GET serviceRoot/Airports?$filter=contains(Location/Address, 'San Francisco')
- Date functions
