### ISSUE TITLE
better support for views translation - return data from _vt tables

### ISSUE THREAD

**Issue by norbertbede** [bxservice/idempiere-rest#117]
issue:
REST API can't get translations for String field types.
GET method doesn't support _vt  views for translation. 

improvement: 
we can improve that to make it return the record from the vt if exists 
so when data requested the REST plugin checks __Vt table existence, if exists, translated data will be returned. (same as print formats)

xref
https://mattermost.idempiere.org/idempiere/pl/f3kb7jzhq7bj9nu9gsjcqi9gko

**Comment by d-ruiz** [comment]
Commit: https://github.com/bxservice/idempiere-rest/commit/6e9e120dca21b5792890a8f1f2b2f8a73514acca

You can test and tell me your findings.
