### ISSUE TITLE
Create Child recursively in Model 

### ISSUE THREAD

**Issue by victorsuarezis** [bxservice/idempiere-rest#121]
When creating children it only does it at one level, it doesn't create the records when it comes to sending children of children
Example: 
- Invoice
     - Invoice Line
          - Landed Costs
In this example, only the Invoices and Lines are created, without the Landed Costs

**Comment by d-ruiz** [comment]
Hi @victorsuarezis, thanks for the contribution. Could you please check my comments in the pull request.

Best regards,
Diego

**Comment by d-ruiz** [comment]
Hi @victorsuarezis. The requested changes were very small so I merge your ticket and did them myself. Thanks a lot for your contribution, the improvement is amazing!

**Comment by victorsuarezis** [comment]
Hi @d-ruiz. Sorry, I had not seen the notification. Thank you very much

**Comment by victorsuarezis** [comment]
Thanks @d-ruiz . To take advantage of the functionality, when making the POST to create records, an array inside another is added to the JSON, to send child records recursively.
For example:

- Invoice
    - Invoice Line
        - Landed Costs
