### ISSUE TITLE
Expand tables 2 values as parameters parameters (f.i fact_acct)

### ISSUE THREAD

**Issue by d-ruiz** [bxservice/idempiere-rest#129]
At the moment the expand takes the FK of the expanded table as the expand value. 

For instance, get/product?$expand=ProductPrice
Checks for the M_Product_ID column in ProductPrice to do the expand, if it does not exist, it does not expand anything. 

This is not useful for tables such as fact_acct, where you have a combination of ad_table/record_id, because the FK with the same name does not exist. 

the idea of this ticket is to add that functionality to the REST API. 

Allowing expanding table with two parameters with the following syntax: 
?expand=fact_acct(fact_acct.ad_table_id=318,fact_acct.record_id=c_invoice.c_invoice_id)

xref: https://mattermost.idempiere.org/idempiere/pl/ttaistacqp8z8quwpmw716wbwy

**Comment by CarlosRuiz-globalqss** [comment]
@d-ruiz / @norbertbede / igorpojzl

I proposed this syntax in mattermost:
```?expand=fact_acct(fact_acct.ad_table_id=318,fact_acct.record_id=c_invoice.c_invoice_id)```

But I think is not good.

Instead of that I would propose this syntax:

1 - the actual case:
```ad_user?$expand=c_order```
the table c_order is expanded using by c_order.ad_user_id
this is what is working now, and it must keep working the same (backward compatibility)

2 - and we can extend that expand syntax as this:
```ad_user?$expand=c_order.salesrep_id```
in this case the table c_order would be expanded using salesrep_id - example useful if I want to calculate the commissions of a salesman
here the code must validate that salesrep_id is a correct reference to the table ad_user, otherwise do not allow this column as FK

using ```ad_user?$expand=c_order.ad_user_id``` would be the same as the 1st case

3 - and for the case of expanding using table_id+record_id
```c_invoice?$expand=fact_acct.record_id```
we detect that we want to expand using record_id as FK, and we know the ad_table_id of c_invoice (the parent table) so we expand here with ```fact_acct..ad_table_id=318 and fact_acct.record_id=c_invoice.c_invoice_id```


WDYT?

**Comment by norbertbede** [comment]
Hi @CarlosRuiz-globalqss, let see use cases i found  (including multi-level expend another requested issue)

1. the next view "snippet" explain what we want REPLACE with $expand
============================================================================================================================

ad1. the 1st lateral get products attributes. instead view and special join we want to get with $Expand M_Product $select name, value, isconfigurableattribute
ad2. this is not reproducible in vanilla version. we have implemented @deepak DMS solution we started design together in 2015 - 
    in this case we would like get all contents related a product. let saz product has 

    `$EXPAND=rv_dms_published.record_id( $SELECT=name, rl,ad_table_id, record_id,fileextension,mimetype $filter=fileextension="images" $LIMIT 3 $ORDERBY=name )`

```
SELECT 
    m_product_id,
    pa_json.product_attributes_json,
    dms_json.dmsdata
FROM m_product_xx pws
LEFT JOIN LATERAL ( SELECT json_agg(pa2.*) AS product_attributes_json
      FROM ( SELECT pa.m_attribute_id,
               pa.name,
               pa.value,
               pa.isconfigurableattribute
              FROM m_product_attribute_v pa
             WHERE pa.m_product_id = p.m_product_id) pa2) pa_json ON true
LEFT JOIN LATERAL ( SELECT json_agg(dms2.*) AS dmsdata
      FROM ( SELECT dms.url,
               dms.ad_table_id,
               dms.record_id,
               dms.fileextension,
               dms.mimetype
              FROM rv_dms_published dms
             WHERE dms.ad_table_id = 208::numeric AND dms.record_id = p.m_product_id) dms2) dms_json ON true;
```



2. more complex example - includes almost all improvments - main object is c_invoice - let say we would like get complex response around customer invoice - something like composite data.
============================================================================================================================

this is too complex, probably, slow, but good illustrates possible case

        PSEUDO LOGIC

        C_Invoice $filter = issotrx=true $limit 10

            $EXPAND (1st level) = C_InvoiceLine - this return list of invoice lines including Product columns and Images from DMS, 

                    $EXPAN=M_Product $select=name, description (2nd level) 
                        $expand=M_Product_Acct (3th level) M_Product_Acct - this illustrate, how we would like to get accounting rules for this product
                        $expand=rv_dms_published.record_id (3th level) DMS_Content - return invoice line product attached images from DMS module. - return only first 3, filter png, orderby=name


            `$EXPAND =C_InvoiceTax` - this return tax records for - simple 1st level expand

            `$EXPAND =Fact_Acct.record_id`  - this entitled to return, all fact records for an invoice (talbe/record identifier FK)

**Comment by igorpojzl** [comment]
@CarlosRuiz-globalqss 
Syntax looks correct. I have 3 Questions.

1.  In case 2,3 in wrong FK will it return 400 - Bad Request?
2. What will be the name of expanded array in return json? 
3. Can we Use case 1 and case 2 in one query? for example : ad_user?$expand=c_order,c_order.salesrep_id

**Comment by d-ruiz** [comment]
Hi @norbertbede, you're mixing two tickets here, so I'll reply to some of your comments on the [proper ticket](https://github.com/bxservice/idempiere-rest/issues/130) to be able to track the discussion later on. 

@igorpojzl 

1 - Yes, if the wrong FK is sent, it is considered a bad request.
2 - This depends on the request, I would say initially, we keep it like it is for standard expand and if a special case such as c_orderline.salesrep_id is requested, the array name would be the whole string "c_orderline.salesrep_id".
3 - Should be possible

**Comment by d-ruiz** [comment]
Documentation: https://wiki.idempiere.org/en/REST_Web_Services#Query_Option_.24expand
