### ISSUE TITLE
Multi-level expand

### ISSUE THREAD

**Issue by d-ruiz** [bxservice/idempiere-rest#130]
Expand is currently limited to going one level deeper. 

The idea of this ticket is to improve that by allowing multi level expand, similar to what Microsoft and SAP do.
https://docs.microsoft.com/en-us/odata/webapi/odata-expand#expand-depth

The syntax is: 
?$expand=course($expand=Department)

xref: https://mattermost.idempiere.org/idempiere/pl/p8c7hirru3rkuxida14s1by8mc

**Comment by d-ruiz** [comment]
Hi @norbertbede, coming from https://github.com/bxservice/idempiere-rest/issues/129.

>     more complex example - includes almost all improvments - main object is c_invoice - let say we would like get complex response around customer invoice - something like composite data.
>     ============================================================================================================================
> 
> this is too complex, probably, slow, but good illustrates possible case
> 
>     PSEUDO LOGIC
> 
>     C_Invoice $filter = issotrx=true $limit 10
> 
>         $EXPAND (1st level) = C_InvoiceLine - this return list of invoice lines including Product columns and Images from DMS, 
> 
>                 $EXPAN=M_Product $select=name, description (2nd level) 
>                     $expand=M_Product_Acct (3th level) M_Product_Acct - this illustrate, how we would like to get accounting rules for this product
>                     $expand=rv_dms_published.record_id (3th level) DMS_Content - return invoice line product attached images from DMS module. - return only first 3, filter png, orderby=name
> 
> 
>         `$EXPAND =C_InvoiceTax` - this return tax records for - simple 1st level expand
> 
>         `$EXPAND =Fact_Acct.record_id`  - this entitled to return, all fact records for an invoice (talbe/record 

The example you create here is technically not an expand and it is not supported, this would be a new development. 

GET C_Invoice
       EXPAND C_InvoiceLine
                EXPAND M_Product

Expand was originally designed for master>detail relations, that's why it returns arrays. Product is not a detail of order line, is a lookup value, that's different, it will never be an array because each line has one and only one product.

So, the expand logic does not apply in those cases. Multi level is something like.

GET C_Bpartner
         EXPAND AD_User
                   EXPAND R_InterestArea_ID

Those are all master > Detail relations. I'll check the code and discuss it with @CarlosRuiz-globalqss to see if the effort is too big to add what you need (lookup values), otherwise that'd be out of scope.

**Comment by igorpojzl** [comment]
Hi @d-ruiz, @CarlosRuiz-globalqss. 
I checked OData specification and expand is defined as related resources without stating only Master -> Detail relation. In documentation there are both examples Master -> Detail and Detail -> Master.

Models/C_Invoice?$filter=issotrx eq true&$limit=10&expand=C_InvoiceLine($expand=M_Product($select=name,description;$expand= M_Product_Acct, rv_dms_published.record_id($filter=mimetype eq 'image'$orderby=name;$limit=3)), C_InvoiceTax, Fact_Acct.record_id)


http://docs.oasis-open.org/odata/odata/v4.0/os/part2-url-conventions/odata-v4.0-os-part2-url-conventions.html#_Toc372793860

Windows Web Api example
https://learn.microsoft.com/en-us/aspnet/web-api/overview/odata-support-in-aspnet-web-api/using-select-expand-and-value

**Comment by CarlosRuiz-globalqss** [comment]
Yes @igorpojzl - the odata standard defines the expand in both directions, but as you know our implementation is not fully odata compliant.

What @d-ruiz meant is that the actual implementation just expand to details, and expanding to a master is a different request than this ticket.

**Comment by CarlosRuiz-globalqss** [comment]
In the implementation of this issue the semicolon was selected as the separator for operators of the expand option.

This has a problem because there are API gateways that do not support semicolon as a separator, for example Traefik by default changes semicolons to ampersands, see for example:
https://github.com/golang/go/issues/25192

Krakend has also problems with semicolons throwing this error:
http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192

**Comment by CarlosRuiz-globalqss** [comment]
> In the implementation of this issue the semicolon was selected as the separator for operators of the expand option.
> 
> This has a problem because there are API gateways that do not support semicolon as a separator, for example Traefik by default changes semicolons to ampersands, see for example: [golang/go#25192](https://github.com/golang/go/issues/25192)
> 
> Krakend has also problems with semicolons throwing this error: http: URL query contains semicolon, which is no longer a supported separator; parts of the query may be stripped when parsed; see golang.org/issue/25192

Solved with https://github.com/bxservice/idempiere-rest/commit/9f579c237d5f985793254d8ba6949ef610ed2738
