### ISSUE TITLE
Add OIDC access token validation support

### ISSUE THREAD

**Issue by hengsin** [bxservice/idempiere-rest#172]
Add support for authentication using access token from oauth + oidc server (for e.g, keycloak). Since the project is already using jwt library from auth0, perhaps that can be added using https://github.com/auth0/jwks-rsa-java

Access token validation with public key for keycloak:
- https://stackoverflow.com/questions/53543117/how-to-setup-public-key-for-verifying-jwt-tokens-from-keycloak
- https://www.keycloak.org/docs/latest/securing_apps/index.html#other-openid-connect-libraries
- https://github.com/auth0/java-jwt/blob/master/EXAMPLES.md

Another library for this is nimbus from connect2id.com
- https://connect2id.com/products/nimbus-jose-jwt/examples/validating-jwt-access-tokens

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - is this related to exposing the key for external authenticators?

For krakend I needed to add a way to expose the key, so I implemented a [SysConfig IDEMPIERE_REST_EXPOSE_JWK](https://wiki.idempiere.org/en/REST_Web_Services#IDEMPIERE_REST_EXPOSE_JWK) for that, in case of exposing that URL it must not be public, but just accessible for krakend.

Is this proposal something similar?

Also, is there any relationship here with https://github.com/bxservice/idempiere-rest/issues/173 where @alanlesc1 is proposing to implement refresh token?

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - adding here also a note that @norbertbede mentioned [in mattermost rest channel](https://mattermost.idempiere.org/idempiere/pl/mrxq8ud7sib78k89ikg3fadtmc) that he has already an implementation for OAuth2

**Comment by hengsin** [comment]
> Hi @hengsin - is this related to exposing the key for external authenticators?
> 
> For krakend I needed to add a way to expose the key, so I implemented a [SysConfig IDEMPIERE_REST_EXPOSE_JWK](https://wiki.idempiere.org/en/REST_Web_Services#IDEMPIERE_REST_EXPOSE_JWK) for that, in case of exposing that URL it must not be public, but just accessible for krakend.
> 
> Is this proposal something similar?
> 
> Also, is there any relationship here with #173 where @alanlesc1 is proposing to implement refresh token?
No, this is about a third party font end (for e.g, a react client) perform authentication with an oauth server (for e.g keycloak), get the access token response from the oauth server and uses that to call idempiere-rest api (pass as bearer token).

**Comment by hengsin** [comment]
Hi @CarlosRuiz-globalqss , #173 is what's needed to make iDempiere an oauth provider (well, at least part of it), this ticket is the opposite of that, to support authentication using third party oauth provider (and for the specific use case when the authentication is initiated by third party client, not iDempiere).

**Comment by hengsin** [comment]
Have push first draft PR for review and testing.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @hengsin - after the mvn is throwing error:

https://jenkins.idempiere.org/job/idempiere-rest/85/console

(reproducible locally too)

Can you please check?

**Comment by hengsin** [comment]
> Hi @hengsin - after this commit mvn is throwing error:
> 
> https://jenkins.idempiere.org/job/idempiere-rest/85/console
> 
> (reproducible locally too)
> 
> Can you please check?

diff --git a/com.trekglobal.idempiere.rest.api/pom.xml b/com.trekglobal.idempiere.rest.api/pom.xml
index ea09e85..ca2c496 100644
--- a/com.trekglobal.idempiere.rest.api/pom.xml
+++ b/com.trekglobal.idempiere.rest.api/pom.xml
@@ -43,11 +43,4 @@
                        </plugin>
                </plugins>
        </build>
-       <dependencies>
-               <dependency>
-                       <groupId>org.idempiere</groupId>
-                       <artifactId>org.idempiere.webservices</artifactId>
-                       <version>11.0.0-SNAPSHOT</version>
-               </dependency>
-       </dependencies>
 </project>
