### ISSUE TITLE
cannot get inactive data

### ISSUE THREAD

**Issue by uthadehikaru** [bxservice/idempiere-rest#175]
if column isActive='N', the data is not appear. the problem is the hardcoded onlyActiveRecord when get data using query builder. can we remove the filter and using $filter=isactive eq true to show only active record.

**Comment by CarlosRuiz-globalqss** [comment]
I think is better to keep the default  as is, and add a Query option to force returning inactive, something like "includeinactive" as a new query option.

**Comment by CarlosRuiz-globalqss** [comment]
Hi @uthadehikaru - can you please check and test the [pull request 191](https://github.com/bxservice/idempiere-rest/pull/191)

I managed to solve it in a different easier way.

It's almost what you suggested in the ticket description, but still defaults to get just active when not set.

I checked and it seems is how SAP has implemented it too:
https://userapps.support.sap.com/sap/support/knowledge/en/2166571
