### ISSUE TITLE
LookupTypeConverter for findIdbyColumn

### ISSUE THREAD

**Issue by ocurieles** [bxservice/idempiere-rest#216]
Create a new findIdbyColumn to use in a POST as:
"M_Product_ID": {"columnName": "UPC", "value": data["upc"]}

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @ocurieles 

I merged your suggestion with some changes.

The most important change is that I switched to use lookupColumn and lookupValue as the names of those json variables.

The second change is that I added a prevision to throw an error if more than one record is found with the same parameters.
