### ISSUE TITLE
Add Amazon Cognito SSO support to iDempiere

### ISSUE THREAD

**Issue by etantg** [bxservice/idempiere-rest#252]
Add Amazon Cognito SSO support to iDempiere Web Client and Rest API

**Comment by etantg** [comment]
Documentation: https://docs.google.com/document/d/1p5PCtAij18L-PpoMu-aT5WEdnQb1jTowwgHNkfAMmWU/edit?usp=sharing

**Comment by etantg** [comment]
The same configuration works for both SSO in zkwebui and Rest API

**Comment by hengsin** [comment]
#2 - By tenant is more secure and more compliance with https://docs.aws.amazon.com/cognito/latest/developerguide/bp_user-pool-based-multi-tenancy.html . I don't think Deepak's design will works in a real multi tenant environment. He kinds of admit it and promise to improve it later but as of now, that has not happens.

#3 That's the limitation of the basic Cognito service, you need to purchase the advance security feature to include openid scope. oauth2 refers to the web oauth2 authentication by user and not appropriate for API call.

**Comment by CarlosRuiz-globalqss** [comment]
Thanks @hengsin,

About 2) - I tested yesterday the two ways we manage multi-tenant user:
- user in System with roles in multiple tenants - like SuperUser - works fine
- same user email in multiple tenants with roles in every tenant - worked fine too

What cognito suggest is to control access through resources, but as we manage the permissions within iDempiere, I think is not a big deal.

I'm going to merge this ticket as it is, but I think there is room for improvement on that to make it work similar to zkwebui.


Thanks also for clarification about 3).
