### ISSUE TITLE
Implement Rest View schema abstraction on top of iDempiere Model

### ISSUE THREAD

**Issue by hengsin** [bxservice/idempiere-rest#281]
iDempiere model typically has many columns and is using DB naming convention that's not particularly natural in a Json data schema. A common need is to pick a subset of columns for different use case and uses a more json oriented naming for the selected columns.

This ticket is to add a layer of abstraction on top of iDempiere model (term as Rest View) to cater for such need. It can be taken as a way to configure Json schema on top of iDempiere model.

Table Added:
Rest_View
- Name
- AD_Table_ID
- WhereClause (optional filter)

Rest_ViewColumn
- Name
- Rest_View_ID
- AD_Column_ID
- REST_ReferenceView_ID (optional Rest_View for expand master)

Rest_ViewRelated 
- Name
- Rest_View_ID
- REST_RelatedRestView_ID (Rest_View for expand details)
- IsRestAutoExpand (true to auto expand in Get by id request)

Rest_View_Access
- Rest_View access at Role Data Access window

Example 2Pack:
[REST_View.zip](https://github.com/user-attachments/files/18061614/REST_View.zip)

Postman test script for the example 2pack above:
[local_test.postman_environment.json](https://github.com/user-attachments/files/18061617/local_test.postman_environment.json)
[view endpoints.postman_collection.json](https://github.com/user-attachments/files/18061618/view.endpoints.postman_collection.json)

**Comment by hengsin** [comment]
Screen shot of example setup:
![userRoles](https://github.com/user-attachments/assets/93c2f5ea-7f71-42fa-9d88-44da3f0a2e5d)
![users](https://github.com/user-attachments/assets/7d950a82-2a5c-4097-9545-5447ba3609ed)
![users_related](https://github.com/user-attachments/assets/e72ccaea-4160-40a5-a4e1-d0d69d7a03b1)

**Comment by hengsin** [comment]
Example Postman Get Request:

![get user](https://github.com/user-attachments/assets/61769431-7a71-46c0-87fb-b3080baa9df0)

**Comment by hengsin** [comment]
With #290 , using the same models namespace for both table and rest_view resources making it hard to access permission by path. I'm thinking of separating the rest_view access to its own views namespace so that we can use #290 to manage access to models and views separately. WDYT ?

**Comment by CarlosRuiz-globalqss** [comment]
> With #290 , using the same models namespace for both table and rest_view resources making it hard to set access permission by path. I'm thinking of separating the rest_view access to its own views namespace so that we can use #290 to manage access to models and views separately (code wise, it will still be using the same ModelResourceImpl class). WDYT ?

Do you mean using a different endpoint?  something like api/v1/views ?

As this is very new and nobody must be still using it, I'm OK about that (no problem about backward compatibility yet).

But I would like to know what is the problem about access permission by path?  Do you mean the REST_ResourceAccess?  What's the problem there?

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss , yes, api/v1/views and I've implemented the change in my latest commit.

I means to create a separate rest_resource path records for models and views. With models at api/v1/models and rest_view at api/v1/views, we can create separate rest_resource path records for each of the endpoint and that make management of resource path permission easier.

**Comment by hengsin** [comment]
hi @CarlosRuiz-globalqss  and @d-ruiz , this just pop up in my mind today.

Question: with the addition of #290, do your thinks we still need the Rest_View_Access layer ? 

It seems to me that it could be too burdensome to have to manage the 2 layer of permission.

**Comment by d-ruiz** [comment]
Yes @hengsin, you're right. Sounds like it is duplicated now that we have the Rest_Resource_Access permission layer.

Better to manage all access in one single place, also easier to maintain and debug

**Comment by CarlosRuiz-globalqss** [comment]
agree - Rest_Resource_Access is enough
