### ISSUE TITLE
Recommended practice is to always return a JSON object

### ISSUE THREAD

**Issue by CarlosRuiz-globalqss** [bxservice/idempiere-rest#63]
I found a best practice we're not following in our implementation here, there are around 20 points where we're returning arrays, while in other points we return JSON objects.

For example 
* /api/v1/auth/roles returns an array
* /api/v1/models returns an array
* /api/v1/models/c_tax returns an array
* /api/v1/models/c_tax/104 returns an unnamed object

The recommendation is to always return a JSON object, returning arrays is not recommended.

There are interesting links discussing the issues, like:
https://softwareengineering.stackexchange.com/questions/286293/whats-the-best-way-to-return-an-array-as-a-response-in-a-restful-api
Some excerpts:
* If you need to add a count of all records you are already done with the array only approach. 
* See for example [how Django REST Framework handles pagination](https://www.django-rest-framework.org/api-guide/pagination/). If you just use an array you don't have anywhere to put count, next and previous

Another interesting discussion about that:
https://github.com/json-api/json-api/issues/268#issuecomment-56184019

So, proposal is to change the points where we're returning arrays and make them return a JSON object instead, with the array  embedded.

**Comment by d-ruiz** [comment]
Hi @CarlosRuiz-globalqss, is there something missing in this issue or can we close it?
